### ISSUE TITLE
Unreachable code - put items not valuable in magicbox

### ISSUE THREAD

**Issue by ssh1215** [tomcat1983/TartanAdventure#103]
There is the condition checking item is valuable or not
when install items in ItemMagicbox.

- in PlayerExecutionEngine.java
else if(itemToBePutInto instanceof ItemMagicBox && !(itemToPut instanceof Valuable)) {

- in Game.java
else if(itemToBePutInto instanceof ItemMagicBox && !(itemToPut instanceof Valuable)) {

This is an unreachable condition.

All items are valuable.

**Comment by Sibong** [comment]
Bug fixed #120
