### ISSUE TITLE
[omission] When user tries to put the item not matched to the hostable item, the item to be put into should be returned into the inventory

### ISSUE THREAD

**Issue by ssh1215** [tomcat1983/TartanAdventure#108]
Possible matching combinations are below:
[hostable] - [installable]
ItemLock - ItemKey
ItemKeycardReader - keycard
ItemComputer - ItemCpu

When the item to put is not matched, then the item should be returned into the inventory.

**Comment by Sibong** [comment]
Bug fixed #111
