### ISSUE TITLE
The ItemSafe required user input at sever game.

### ISSUE THREAD

**Issue by Sibong** [tomcat1983/TartanAdventure#115]
Implementation required in ItemSafe.java -> open()
@Override
    public Boolean open() {
        Scanner s = new Scanner(System.in);
        gameInterface.println(userId, MessageType.PRIVATE, "Enter the four-digit PIN number.");
        Integer p = Integer.parseInt(s.nextLine());
        if (p.intValue() == this.pin.intValue()) {
        	if (this.installedItem != null) {
        		this.installedItem.setVisible(true);
        		gameInterface.println(userId, MessageType.PRIVATE, "The safe door swings open.");
        		gameInterface.println(userId, MessageType.PRIVATE, "You have revealed a '" + this.installedItem.detailDescription() + "'.");
            }
            return true;
        } else {
        	gameInterface.println(userId, MessageType.PRIVATE, "Incorrect PIN.");
        }
        return false;
    }

**Comment by tomcat1983** [comment]
Fixed in pull request #130
