### ISSUE TITLE
[omission] Explode action is wrong.

### ISSUE THREAD

**Issue by ssh1215** [tomcat1983/TartanAdventure#138]
[Condition]
- ItemDynamite is in current room
- the current room is adjacent to Obscured Room

[reproduce step]
Explode the dynamite

[Expected]
Player should get the point and the dynamite should be disappeared.

Now the dynamite is not disappeared after explosion.

**Comment by Sibong** [comment]
Bug fixed. But dynamite cannot disappear.
A dynamite can be used one time in a related room such as obscured room.

Now, if dynamite used in a room, user got a score only one time.
If second time dynamite used by user, user couldn't get a score.
