### ISSUE TITLE
Config.java need to close fileinputstream

### ISSUE THREAD

**Issue by htak1** [tomcat1983/TartanAdventure#181]
Config.java 

If fileinputstream does not close, it seems that resource busy error occurs when doing github merge.

related findbug message 
edu.cmu.tartan.config.Config.readPropertyFile() may fail to close stream

refer to 
https://stackoverflow.com/questions/5090937/do-i-have-to-close-fileinputstream
https://javarevisited.blogspot.com/2014/10/right-way-to-close-inputstream-file-resource-in-java.html

**Comment by tomcat1983** [comment]
Add codes to close file when program is terminated
