### ISSUE TITLE
Remove if statements in unit test codes

### ISSUE THREAD

**Issue by tomcat1983** [tomcat1983/TartanAdventure#51]
Remove if statements in unit test codes.

ex)
assertTrue(room1.putItem(keyItem));
if(room1.hasItem(keyItem)) {
	keytItem2 = (ItemKey)room1.remove(keyItem);
}
assertEquals(keyItem, keytItem2);

change to
assertTrue(room1.putItem(keyItem));
assertTrue(room1.hasItem(keyItem));
keytItem2 = (ItemKey)room1.remove(keyItem);
assertEquals(keyItem, keytItem2);

**Comment by Sibong** [comment]
You can find #55.
